Koosum/abc 42
FAANG/dcc-portal-frontend pull request #68
Opened 2021-11-10 12:01 UTC by yroochun

2021-11-16 09:49 UTC, Aksh77 commented on src/environments/environment.ts
> +  host: 'https://data.faang.org/api/',
Please revert this change as /data endpoint would work when the API is moved to EC v4

2021-11-16 09:52 UTC, Aksh77 requested changes
Please address the following
1. Remove package-lock.json changes
2. Instead of explicitly checking for the "BovReg" project, make it work universally such that when new pipelines file is added for other projects, it works without having to change the code

2021-11-18 16:20 UTC, yroochun commented
1. package-lock.json file reverted to master version

2. It was already working universally - see getAllPipelinesForProject where 'project name' is passed to url. The 'if' condition was added specifically to avoid the default browser message for unfound url in the console. the 'if' condition has now been removed and EMPTY observable is passed for 404 error - although the need for the empty observable is debatable.

3. Host has been reversed

2021-11-19 09:27 UTC, Aksh77 approved these changes

2021-11-19 09:31 UTC, merged